.PHONY: clean All

All:
	@echo "----------Building project:[ SectionSixChallenge - Debug ]----------"
	@cd "SectionSixChallenge" && "$(MAKE)" -f  "SectionSixChallenge.mk"
clean:
	@echo "----------Cleaning project:[ SectionSixChallenge - Debug ]----------"
	@cd "SectionSixChallenge" && "$(MAKE)" -f  "SectionSixChallenge.mk" clean
