.PHONY: clean All

All:
	@echo "----------Building project:[ SectionSevenChallenge - Debug ]----------"
	@cd "SectionSevenChallenge" && "$(MAKE)" -f  "SectionSevenChallenge.mk"
clean:
	@echo "----------Cleaning project:[ SectionSevenChallenge - Debug ]----------"
	@cd "SectionSevenChallenge" && "$(MAKE)" -f  "SectionSevenChallenge.mk" clean
