.PHONY: clean All

All:
	@echo "----------Building project:[ SectionFourChallenge - Debug ]----------"
	@cd "SectionFourChallenge" && "$(MAKE)" -f  "SectionFourChallenge.mk"
clean:
	@echo "----------Cleaning project:[ SectionFourChallenge - Debug ]----------"
	@cd "SectionFourChallenge" && "$(MAKE)" -f  "SectionFourChallenge.mk" clean
